# Generated by Django 4.2.6 on 2024-04-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momui', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='mom_signup',
        ),
    ]
